name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest pytest-cov coverage

      - name: Run tests and generate coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Ensure the app directory is on PYTHONPATH so imports work
          pytest \
            --cov=app \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            tests/
          coverage run --source=app -m pytest tests/
          coverage xml -o coverage.xml
          sed -i -E 's/<source>.*<\/source>/<source>.<\/source>/g' coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .

      - name: Create SonarCloud project if not exists
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y jq
          PROJECT_KEY=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | tr '/' '_')
          echo "PROJECT_KEY=$PROJECT_KEY" >> $GITHUB_ENV
          PROJECT_NAME="$PROJECT_KEY"
          PROJECT_EXISTS="$(curl -s \
            --header "Authorization: Bearer ${{ secrets.SONAR_TOKEN}}" \
            -X GET "${{ vars.SONAR_HOST_URL }}/api/projects/search?organization=${{ vars.SONAR_ORG }}&projects=$PROJECT_KEY" | jq '.components | length')"
          if ! [[ "$PROJECT_EXISTS" =~ ^[0-9]+$ ]]; then
            echo "Error: Could not determine if SonarCloud project exists."
            exit 1
          fi
          if [ "$PROJECT_EXISTS" -eq "0" ]; then
            echo "Creating SonarCloud project..."
            PROJECT_CREATE="$(curl -s \
              -X POST "${{ vars.SONAR_HOST_URL }}/api/projects/create" \
              --header "Authorization: Bearer ${{ secrets.SONAR_TOKEN}}" \
              -d "organization=${{ vars.SONAR_ORG }}" \
              -d "name=$PROJECT_NAME" \
              -d "project=$PROJECT_KEY" \
              -d "visibility=private" \
              -d "newCodeDefinitionType=days&newCodeDefinitionValue=7")"
            echo "SonarCloud project created: $PROJECT_CREATE"
            curl -s -X POST \
              --header "Authorization: Bearer ${{ secrets.SONAR_TOKEN}}" \
              "${{ vars.SONAR_HOST_URL }}/api/project_branches/rename" \
              -d "organization=${{ vars.SONAR_ORG }}&name=main&project=${PROJECT_KEY}"
          else
            echo "SonarCloud project already exists."
          fi

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORG }}
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
